# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TaskHero' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for TaskHero
    
    pod 'Firebase'
    pod 'Firebase/Auth'
    pod 'FirebaseDatabase'
    pod 'Firebase/Storage'
    pod 'Firebase/Crash'
    pod 'SnapKit'
    
    target 'TaskHeroTests' do
        pod 'Quick'
        pod 'Nimble'
        #  abstract_target 'Tests' do
        #      inherit! :search_paths
        #      target "MyAppTests"
        #      target "MyAppUITests"
        #      
        
    end
end
